// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.ZIPDemographics
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("zip")]
        public long? Zip { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("acsYear")]
        public long? AcsYear { get; set; }

        [JsonProperty("population")]
        public Population Population { get; set; }

        [JsonProperty("income")]
        public Income Income { get; set; }

        [JsonProperty("housing")]
        public Housing Housing { get; set; }

        [JsonProperty("education")]
        public Education Education { get; set; }

        [JsonProperty("employment")]
        public Employment Employment { get; set; }

        [JsonProperty("race")]
        public Race Race { get; set; }

        [JsonProperty("formatted")]
        public Formatted Formatted { get; set; }
    }

    public partial class Education
    {
        [JsonProperty("collegeEducatedPct")]
        public double? CollegeEducatedPct { get; set; }
    }

    public partial class Employment
    {
        [JsonProperty("laborForce")]
        public long? LaborForce { get; set; }

        [JsonProperty("unemploymentRate")]
        public double? UnemploymentRate { get; set; }
    }

    public partial class Formatted
    {
        [JsonProperty("medianHouseholdIncome")]
        public string MedianHouseholdIncome { get; set; }

        [JsonProperty("perCapitaIncome")]
        public string PerCapitaIncome { get; set; }

        [JsonProperty("medianHomeValue")]
        public string MedianHomeValue { get; set; }

        [JsonProperty("medianRent")]
        public string MedianRent { get; set; }
    }

    public partial class Housing
    {
        [JsonProperty("medianHomeValue")]
        public long? MedianHomeValue { get; set; }

        [JsonProperty("medianRent")]
        public long? MedianRent { get; set; }

        [JsonProperty("totalUnits")]
        public long? TotalUnits { get; set; }

        [JsonProperty("homeOwnershipRate")]
        public double? HomeOwnershipRate { get; set; }
    }

    public partial class Income
    {
        [JsonProperty("medianHousehold")]
        public long? MedianHousehold { get; set; }

        [JsonProperty("perCapita")]
        public long? PerCapita { get; set; }
    }

    public partial class Population
    {
        [JsonProperty("total")]
        public long? Total { get; set; }

        [JsonProperty("male")]
        public long? Male { get; set; }

        [JsonProperty("female")]
        public long? Female { get; set; }

        [JsonProperty("medianAge")]
        public double? MedianAge { get; set; }
    }

    public partial class Race
    {
        [JsonProperty("white")]
        public Asian White { get; set; }

        [JsonProperty("asian")]
        public Asian Asian { get; set; }
    }

    public partial class Asian
    {
        [JsonProperty("count")]
        public long? Count { get; set; }

        [JsonProperty("percent")]
        public double? Percent { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
